### ISSUE TITLE
Fix the issue with the sample dataset

### ISSUE THREAD

**Issue by terry07** [idiap/wmil-sgd#2]
Trying to execute your example, i take the next error:

--> TypeError: a bytes-like object is required, not 'str'

Please provide a proper modification for Python 3 or convert dataset to another format.

Kind regards,

**Comment by nik0spapp** [comment]
Thanks for the suggestion! I will consider storing it for Python 3 when time allows. This dataset was created a long time ago but it should be possible to load it with older versions of python.

**Comment by nik0spapp** [comment]
Hi, it turns out that the file can be loaded with Python 3 as follows:

```
$ python3
>>> import pickle 
>>> x = pickle.load(open("features/ted_comments.p","rb"), encoding="latin1") 
```

Let me know if that is not working for you, closing the ticket for now.
